import React, { useState } from "react";
import { Sparkles, Sliders, Eye, Copy, Check, Palette, Code2, RefreshCw } from "lucide-react";
import { playClickSound, playSuccessSound, playHoverSound } from "../utils/audio";

// Helper for WCAG Contrast Calculation
function getLuminance(r, g, b) {
  const [rs, gs, bs] = [r, g, b].map((c) => {
    c = c / 255;
    return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
  });
  return 0.2126 * rs + 0.7152 * gs + 0.0722 * bs;
}

function hexToRgb(hex) {
  let c = hex.replace("#", "");
  if (c.length === 3) {
    c = c.split("").map((x) => x + x).join("");
  }
  const num = parseInt(c, 16);
  return {
    r: (num >> 16) & 255,
    g: (num >> 8) & 255,
    b: num & 255,
  };
}

function calculateContrastRatio(hex1, hex2) {
  try {
    const rgb1 = hexToRgb(hex1);
    const rgb2 = hexToRgb(hex2);
    const lum1 = getLuminance(rgb1.r, rgb1.g, rgb1.b);
    const lum2 = getLuminance(rgb2.r, rgb2.g, rgb2.b);
    const brightest = Math.max(lum1, lum2);
    const darkest = Math.min(lum1, lum2);
    return ((brightest + 0.05) / (darkest + 0.05)).toFixed(2);
  } catch (e) {
    return "4.50";
  }
}

export default function FrontendLab() {
  const [activeTab, setActiveTab] = useState("glass");

  // Glassmorphism state
  const [blur, setBlur] = useState(16);
  const [opacity, setOpacity] = useState(25);
  const [borderAlpha, setBorderAlpha] = useState(15);
  const [glowColor, setGlowColor] = useState("#38bdf8");
  const [glowSpread, setGlowSpread] = useState(20);
  const [copiedCSS, setCopiedCSS] = useState(false);

  // A11y Contrast Checker state
  const [fgColor, setFgColor] = useState("#38bdf8");
  const [bgColor, setBgColor] = useState("#07090e");

  const contrastRatio = calculateContrastRatio(fgColor, bgColor);
  const ratioNum = parseFloat(contrastRatio);
  const aaNormal = ratioNum >= 4.5;
  const aaLarge = ratioNum >= 3.0;
  const aaaNormal = ratioNum >= 7.0;
  const aaaLarge = ratioNum >= 4.5;

  const generatedCSS = `/* Generated by Abinash Glassmorphism Engine */
background: rgba(15, 23, 42, ${opacity / 100});
backdrop-filter: blur(${blur}px);
-webkit-backdrop-filter: blur(${blur}px);
border: 1px solid rgba(255, 255, 255, ${borderAlpha / 100});
box-shadow: 0 8px 32px 0 ${glowColor}${Math.round((glowSpread / 100) * 255).toString(16).padStart(2, "0")};
border-radius: 16px;`;

  const handleCopyCSS = () => {
    navigator.clipboard.writeText(generatedCSS);
    setCopiedCSS(true);
    playSuccessSound();
    setTimeout(() => setCopiedCSS(false), 2500);
  };

  return (
    <section id="lab" className="py-20 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
      
      {/* Section Header */}
      <div className="text-center max-w-3xl mx-auto space-y-3 mb-12">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 text-xs font-mono">
          <Sparkles className="w-3.5 h-3.5" />
          <span>Interactive Playground</span>
        </div>
        <h2 className="text-3xl sm:text-4xl font-extrabold font-heading text-slate-100">
          Frontend <span className="gradient-text">Developer Lab</span>
        </h2>
        <p className="text-slate-400 text-sm sm:text-base">
          Test drive live interactive tools designed right in the browser. Tweak variables in real time and extract production-ready code.
        </p>
      </div>

      {/* Mode Selector Tabs */}
      <div className="flex justify-center mb-8">
        <div className="inline-flex p-1.5 rounded-2xl bg-slate-900/80 border border-slate-800 backdrop-blur-md gap-2">
          <button
            onClick={() => {
              playClickSound();
              setActiveTab("glass");
            }}
            onMouseEnter={playHoverSound}
            className={`flex items-center gap-2 px-5 py-2 rounded-xl text-xs sm:text-sm font-semibold transition-all cursor-pointer ${
              activeTab === "glass"
                ? "bg-gradient-to-r from-cyan-500 to-indigo-600 text-slate-950 shadow-md"
                : "text-slate-400 hover:text-white"
            }`}
          >
            <Sliders className="w-4 h-4" />
            <span>CSS Glass & Glow Generator</span>
          </button>

          <button
            onClick={() => {
              playClickSound();
              setActiveTab("contrast");
            }}
            onMouseEnter={playHoverSound}
            className={`flex items-center gap-2 px-5 py-2 rounded-xl text-xs sm:text-sm font-semibold transition-all cursor-pointer ${
              activeTab === "contrast"
                ? "bg-gradient-to-r from-cyan-500 to-indigo-600 text-slate-950 shadow-md"
                : "text-slate-400 hover:text-white"
            }`}
          >
            <Eye className="w-4 h-4" />
            <span>WCAG Contrast Checker</span>
          </button>
        </div>
      </div>

      {/* TAB 1: Glassmorphism Builder */}
      {activeTab === "glass" && (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center bg-[#0d121f]/90 border border-slate-800 p-6 sm:p-8 rounded-3xl backdrop-blur-md shadow-2xl">
          
          {/* Controls */}
          <div className="lg:col-span-6 space-y-5">
            <h3 className="text-lg font-bold font-heading text-slate-100 flex items-center gap-2">
              <Sliders className="w-5 h-5 text-cyan-400" />
              <span>Glass Shader Controls</span>
            </h3>

            {/* Blur Slider */}
            <div className="space-y-1.5">
              <div className="flex justify-between text-xs font-mono">
                <span className="text-slate-400">Backdrop Blur</span>
                <span className="text-cyan-400 font-bold">{blur}px</span>
              </div>
              <input
                type="range"
                min="0"
                max="40"
                value={blur}
                onChange={(e) => setBlur(Number(e.target.value))}
                className="w-full accent-cyan-400 bg-slate-800 h-2 rounded-lg cursor-pointer"
              />
            </div>

            {/* Opacity Slider */}
            <div className="space-y-1.5">
              <div className="flex justify-between text-xs font-mono">
                <span className="text-slate-400">Surface Fill Opacity</span>
                <span className="text-cyan-400 font-bold">{opacity}%</span>
              </div>
              <input
                type="range"
                min="5"
                max="90"
                value={opacity}
                onChange={(e) => setOpacity(Number(e.target.value))}
                className="w-full accent-cyan-400 bg-slate-800 h-2 rounded-lg cursor-pointer"
              />
            </div>

            {/* Border Alpha Slider */}
            <div className="space-y-1.5">
              <div className="flex justify-between text-xs font-mono">
                <span className="text-slate-400">Border Highlight</span>
                <span className="text-cyan-400 font-bold">{borderAlpha}%</span>
              </div>
              <input
                type="range"
                min="0"
                max="80"
                value={borderAlpha}
                onChange={(e) => setBorderAlpha(Number(e.target.value))}
                className="w-full accent-cyan-400 bg-slate-800 h-2 rounded-lg cursor-pointer"
              />
            </div>

            {/* Glow Color & Spread */}
            <div className="grid grid-cols-2 gap-4 pt-1">
              <div className="space-y-1.5">
                <label className="text-xs font-mono text-slate-400">Glow Accent</label>
                <div className="flex items-center gap-2">
                  <input
                    type="color"
                    value={glowColor}
                    onChange={(e) => setGlowColor(e.target.value)}
                    className="w-10 h-10 rounded-xl bg-transparent border-0 cursor-pointer"
                  />
                  <span className="text-xs font-mono text-slate-300">{glowColor}</span>
                </div>
              </div>
              <div className="space-y-1.5">
                <div className="flex justify-between text-xs font-mono">
                  <span className="text-slate-400">Glow Intensity</span>
                  <span className="text-cyan-400 font-bold">{glowSpread}%</span>
                </div>
                <input
                  type="range"
                  min="0"
                  max="70"
                  value={glowSpread}
                  onChange={(e) => setGlowSpread(Number(e.target.value))}
                  className="w-full accent-cyan-400 bg-slate-800 h-2 rounded-lg cursor-pointer mt-3"
                />
              </div>
            </div>

            {/* Copy CSS Button */}
            <button
              onClick={handleCopyCSS}
              className="w-full flex items-center justify-center gap-2 py-3 rounded-xl bg-gradient-to-r from-cyan-500 to-indigo-600 hover:from-cyan-400 hover:to-indigo-500 text-slate-950 font-bold text-xs shadow-lg shadow-cyan-500/20 transition-all cursor-pointer"
            >
              {copiedCSS ? (
                <>
                  <Check className="w-4 h-4 text-slate-950" />
                  <span>Copied CSS to Clipboard!</span>
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4 text-slate-950" />
                  <span>Copy Production CSS</span>
                </>
              )}
            </button>
          </div>

          {/* Live Render & Code Output */}
          <div className="lg:col-span-6 space-y-4">
            
            {/* Live Interactive Preview Box */}
            <div className="relative h-64 rounded-2xl bg-gradient-to-tr from-cyan-900/40 via-purple-900/30 to-rose-900/40 border border-slate-800 flex items-center justify-center p-6 overflow-hidden">
              
              {/* Background decorative circles to test blur */}
              <div className="absolute w-24 h-24 bg-cyan-400/70 rounded-full top-4 left-6 blur-sm" />
              <div className="absolute w-20 h-20 bg-pink-500/70 rounded-full bottom-6 right-8 blur-sm" />
              <div className="absolute w-16 h-16 bg-amber-400/80 rounded-full top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2" />

              {/* Dynamic Glass Container */}
              <div
                style={{
                  background: `rgba(15, 23, 42, ${opacity / 100})`,
                  backdropFilter: `blur(${blur}px)`,
                  WebkitBackdropFilter: `blur(${blur}px)`,
                  border: `1px solid rgba(255, 255, 255, ${borderAlpha / 100})`,
                  boxShadow: `0 12px 40px 0 ${glowColor}${Math.round((glowSpread / 100) * 255).toString(16).padStart(2, "0")}`,
                  borderRadius: "16px",
                }}
                className="relative z-10 p-5 w-full max-w-sm text-center space-y-2 text-white"
              >
                <div className="w-8 h-8 mx-auto rounded-xl bg-white/20 flex items-center justify-center">
                  <Sparkles className="w-4 h-4 text-cyan-300" />
                </div>
                <h4 className="font-bold font-heading text-sm">Glassmorphic UI Element</h4>
                <p className="text-[11px] text-slate-200 opacity-90 leading-tight">
                  Real-time GPU accelerated backdrop shader with custom optical refraction.
                </p>
              </div>
            </div>

            {/* Generated CSS Box */}
            <div className="p-3.5 bg-slate-950/80 rounded-2xl border border-slate-800 font-mono-code text-[11px] text-slate-300 overflow-x-auto">
              <pre>{generatedCSS}</pre>
            </div>

          </div>
        </div>
      )}

      {/* TAB 2: WCAG A11y Contrast Calculator */}
      {activeTab === "contrast" && (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center bg-[#0d121f]/90 border border-slate-800 p-6 sm:p-8 rounded-3xl backdrop-blur-md shadow-2xl">
          
          {/* Controls */}
          <div className="lg:col-span-5 space-y-6">
            <h3 className="text-lg font-bold font-heading text-slate-100 flex items-center gap-2">
              <Eye className="w-5 h-5 text-cyan-400" />
              <span>WCAG Color Contrast Validator</span>
            </h3>
            
            <p className="text-xs text-slate-400">
              Ensuring web accessibility for visual impairments by testing against WCAG 2.1 AA and AAA luminance standards.
            </p>

            <div className="space-y-4">
              <div className="space-y-1.5">
                <label className="text-xs font-mono text-slate-400">Foreground / Text Color</label>
                <div className="flex items-center gap-3">
                  <input
                    type="color"
                    value={fgColor}
                    onChange={(e) => setFgColor(e.target.value)}
                    className="w-10 h-10 rounded-xl bg-transparent border-0 cursor-pointer"
                  />
                  <input
                    type="text"
                    value={fgColor}
                    onChange={(e) => setFgColor(e.target.value)}
                    className="px-3 py-1.5 bg-slate-950 border border-slate-800 rounded-xl font-mono text-xs text-slate-200"
                  />
                </div>
              </div>

              <div className="space-y-1.5">
                <label className="text-xs font-mono text-slate-400">Background Surface Color</label>
                <div className="flex items-center gap-3">
                  <input
                    type="color"
                    value={bgColor}
                    onChange={(e) => setBgColor(e.target.value)}
                    className="w-10 h-10 rounded-xl bg-transparent border-0 cursor-pointer"
                  />
                  <input
                    type="text"
                    value={bgColor}
                    onChange={(e) => setBgColor(e.target.value)}
                    className="px-3 py-1.5 bg-slate-950 border border-slate-800 rounded-xl font-mono text-xs text-slate-200"
                  />
                </div>
              </div>
            </div>

            {/* Presets */}
            <div className="space-y-2 pt-2">
              <span className="text-[11px] font-mono text-slate-500">Quick Presets:</span>
              <div className="flex flex-wrap gap-2">
                {[
                  { name: "Cyan on Dark", fg: "#38bdf8", bg: "#07090e" },
                  { name: "White on Indigo", fg: "#ffffff", bg: "#312e81" },
                  { name: "Dark on Amber", fg: "#18181b", bg: "#fbbf24" },
                  { name: "Emerald Matrix", fg: "#4ade80", bg: "#022c22" },
                ].map((p, idx) => (
                  <button
                    key={idx}
                    onClick={() => {
                      playClickSound();
                      setFgColor(p.fg);
                      setBgColor(p.bg);
                    }}
                    className="px-2.5 py-1 rounded-lg bg-slate-800 hover:bg-slate-700 text-[11px] font-mono text-slate-300"
                  >
                    {p.name}
                  </button>
                ))}
              </div>
            </div>
          </div>

          {/* Results & Live Simulation */}
          <div className="lg:col-span-7 space-y-6">
            
            {/* Big Ratio Display */}
            <div className="p-6 rounded-2xl bg-slate-950/80 border border-slate-800 flex items-center justify-between">
              <div>
                <span className="text-xs font-mono uppercase text-slate-400">Calculated Contrast Ratio</span>
                <div className="text-4xl font-extrabold font-mono text-cyan-400">{contrastRatio} : 1</div>
              </div>
              <div className={`px-4 py-2 rounded-xl text-xs font-bold font-mono border ${
                ratioNum >= 7.0
                  ? "bg-emerald-500/20 text-emerald-400 border-emerald-500/40"
                  : ratioNum >= 4.5
                  ? "bg-cyan-500/20 text-cyan-400 border-cyan-500/40"
                  : "bg-rose-500/20 text-rose-400 border-rose-500/40"
              }`}>
                {ratioNum >= 7.0 ? "WCAG AAA PASS" : ratioNum >= 4.5 ? "WCAG AA PASS" : "FAIL (Low Contrast)"}
              </div>
            </div>

            {/* Compliance Matrix */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 font-mono">
              <div className="p-3 rounded-xl bg-slate-900/80 border border-slate-800 text-center">
                <div className="text-[11px] text-slate-400">AA Normal</div>
                <div className="text-xs font-semibold text-slate-500">Req: 4.5:1</div>
                <div className={`mt-1 font-bold text-xs ${aaNormal ? "text-emerald-400" : "text-rose-400"}`}>
                  {aaNormal ? "PASS ✓" : "FAIL ✕"}
                </div>
              </div>

              <div className="p-3 rounded-xl bg-slate-900/80 border border-slate-800 text-center">
                <div className="text-[11px] text-slate-400">AA Large</div>
                <div className="text-xs font-semibold text-slate-500">Req: 3.0:1</div>
                <div className={`mt-1 font-bold text-xs ${aaLarge ? "text-emerald-400" : "text-rose-400"}`}>
                  {aaLarge ? "PASS ✓" : "FAIL ✕"}
                </div>
              </div>

              <div className="p-3 rounded-xl bg-slate-900/80 border border-slate-800 text-center">
                <div className="text-[11px] text-slate-400">AAA Normal</div>
                <div className="text-xs font-semibold text-slate-500">Req: 7.0:1</div>
                <div className={`mt-1 font-bold text-xs ${aaaNormal ? "text-emerald-400" : "text-rose-400"}`}>
                  {aaaNormal ? "PASS ✓" : "FAIL ✕"}
                </div>
              </div>

              <div className="p-3 rounded-xl bg-slate-900/80 border border-slate-800 text-center">
                <div className="text-[11px] text-slate-400">AAA Large</div>
                <div className="text-xs font-semibold text-slate-500">Req: 4.5:1</div>
                <div className={`mt-1 font-bold text-xs ${aaaLarge ? "text-emerald-400" : "text-rose-400"}`}>
                  {aaaLarge ? "PASS ✓" : "FAIL ✕"}
                </div>
              </div>
            </div>

            {/* Live Readability Preview Box */}
            <div
              style={{ backgroundColor: bgColor, color: fgColor }}
              className="p-6 rounded-2xl border border-slate-700/80 shadow-lg space-y-2 transition-all"
            >
              <h4 className="text-lg font-bold font-heading">Sample Headline Preview</h4>
              <p className="text-xs sm:text-sm leading-relaxed">
                This is a real-time rendered paragraph simulating typography contrast under varying light conditions and display color profiles.
              </p>
            </div>

          </div>
        </div>
      )}

    </section>
  );
}

